analysis_time_stamp: 01/21/2025, 14:31:04
configs_folder: configs/
data_paths:
  '1200': data/947__M1M2_1200_cells_start_73h/
  '150': data/944__M1M2_150_cells_Start_73h/
  '300': data/945__M1M2_300_cells_start_73h/
  '600': data/946__M1M2_600_cells_start_73h/
  ending: _shape.json
dict_channel:
  BF: 0
  Mesp1: 1
  Mesp2: 2
movie_paths:
  '1200': /path/to/zenodo/folder/Figure_2_S2/Figure_2_movies/947__M1M2_1200_cells_start_73h/
  '150': /path/to/zenodo/folder/Figure_2_S2/Figure_2_movies/944__M1M2_150_cells_Start_73h/
  '300': /path/to/zenodo/folder/Figure_2_S2/Figure_2_movies/945__M1M2_300_cells_start_73h/
  '600': /path/to/zenodo/folder/Figure_2_S2/Figure_2_movies/946__M1M2_600_cells_start_73h/
  ending: .tiff
multipolarity_analysis:
  channel_OI: Mesp2
  folders_OI:
  - all
outliers:
  '1200':
    B10:
    - 47
    - 48
    - 49
    B11:
    - 46
    B2:
    - 33
    - 34
    - 48
    - 49
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    B3:
    - 9
    B5:
    - 45
    - 48
    B6:
    - 49
    - 50
    B7:
    - 24
    - 25
    - 29
    - 30
    - 31
    - 32
    - 34
    - 35
    - 36
    B8:
    - 34
    C10:
    - 34
    - 35
    - 36
    C11:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 32
    - 33
    C2:
    - 34
    C7:
    - 34
    - 35
    - 36
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    C9:
    - 48
    - 49
    D10:
    - 35
    D11:
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    D3:
    - 37
    - 38
    - 39
    D4:
    - 35
    - 36
    - 62
    - 63
    - 64
    D5:
    - 36
    D8:
    - 68
    - 69
    - 70
    D9:
    - 34
    - 48
    - 49
    - 50
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    E10:
    - 36
    - 37
    - 38
    E2:
    - 34
    - 35
    - 39
    - 40
    - 41
    - 61
    - 66
    - 67
    - 68
    - 69
    - 70
    E3:
    - 37
    - 38
    - 39
    E4:
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    E5:
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 52
    - 53
    E6:
    - 36
    - 37
    E7:
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    F10:
    - 33
    - 34
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    F2:
    - 24
    - 25
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    F3:
    - 34
    - 35
    - 36
    - 37
    - 55
    F4:
    - 37
    - 38
    - 62
    - 63
    - 64
    - 65
    - 66
    - 67
    F6:
    - 36
    - 37
    - 38
    - 55
    - 56
    - 57
    F7:
    - 35
    - 36
    - 37
    - 38
    - 52
    - 53
    - 54
    F9:
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 50
    - 51
    - 52
    - 53
    G10:
    - 58
    G2:
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 50
    - 51
    - 52
    - 61
    - 62
    - 63
    - 64
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    G3:
    - 32
    - 33
    - 34
    - 35
    - 36
    G4:
    - 32
    - 33
    - 34
    - 35
    - 36
    G5:
    - 32
    - 33
    G6:
    - 24
    - 25
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    G7:
    - 32
    - 33
    G8:
    - 1
    - 2
    - 3
    - 4
    - 13
    - 15
    - 16
    - 20
    - 21
    - 24
    - 25
    - 26
    - 27
    - 29
    - 30
    - 31
  '150':
    B10:
    - 45
    - 46
    B11:
    - 47
    - 48
    B2:
    - 44
    B9:
    - 49
    - 52
    C10:
    - 44
    C3:
    - 53
    C9:
    - 48
    - 49
    D11:
    - 48
    - 49
    E2:
    - 44
    - 48
    E3:
    - 41
    - 42
    F10:
    - 43
    - 44
    - 46
    F4:
    - 53
    F7:
    - 52
    F9:
    - 42
    G3:
    - 48
    - 49
    G4:
    - 42
    - 43
    G9:
    - 44
  '300':
    B3:
    - 47
    - 48
    - 49
    B7:
    - 42
    - 43
    C3:
    - 5
    - 6
    - 14
    - 15
    - 16
    - 17
    - 18
    C6:
    - 50
    D2:
    - 48
    - 49
    - 50
    - 51
    - 52
    - 56
    - 57
    D5:
    - 47
    D9:
    - 56
    E11:
    - 51
    E5:
    - 48
    F2:
    - 44
    F7:
    - 52
    - 53
    - 54
    - 55
    - 67
    - 68
    - 69
    - 70
    G10:
    - 47
    - 48
    G2:
    - 51
    - 52
    - 53
    - 54
    G4:
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
  '600':
    B10:
    - 50
    B4:
    - 48
    - 49
    B7:
    - 66
    - 67
    - 68
    - 59
    C10:
    - 47
    C3:
    - 47
    - 48
    C4:
    - 49
    - 50
    - 51
    C6:
    - 48
    - 49
    C9:
    - 45
    D10:
    - 47
    D2:
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    D5:
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    E10:
    - 49
    E11:
    - 47
    - 48
    - 49
    E2:
    - 43
    - 44
    - 45
    - 49
    F2:
    - 48
    - 49
    - 50
    - 51
    F6:
    - 54
    G3:
    - 47
    G4:
    - 55
    - 56
    - 57
    - 58
    - 59
    G9:
    - 44
    - 45
    - 46
    - 47
results_folder: plots/
